a3_starter_code/a3_starter_code-main/projectfile/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
#new imports:
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db

#create a blueprint
auth_bp = Blueprint('auth', __name__ )

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            userName = register.userName.data
            password = register.password.data
            emailid = register.emailid.data
            contactNumber = register.contactNumber.data
            address = register.address.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.userName==userName))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(password)
            #create a new User model object
            new_user = User(userName=userName, password_hash=pwd_hash, emailid=emailid, contactNumber=contactNumber, address=address)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('user.html', form=register, heading='Register')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        userName = login_form.userName.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.userName==userName))
        #if there is no user with that name
        if user is None:
            error = 'Incorrect username'#could be a security risk to give this much info away
        #check the password - notice password hash function
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error = 'Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

a3_starter_code/a3_starter_code-main/projectfile/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Event, Booking
from . import db
from flask_login import login_required, current_user
mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    events = db.session.scalars(db.select(Event)).all()    
    return render_template('index.html', events=events, selected_category=None)

@mainbp.route('/search')
def search():
    if request.args['search'] and request.args['search'] != "":
        print(request.args['search'])
        query = "%" + request.args['search'] + "%"
        events = db.session.scalars(db.select(Event).where(Event.eventName.like(query)))
        return render_template('index.html', events=events)
    else:
        return render_template('index.html', events=events)
    
@mainbp.route('/history')
@login_required
def history():
    # Query the database for the current user's bookings
    bookings = Booking.query.filter_by(userid=current_user.id).all()
    return render_template('bhistory.html', bookings=bookings)

a3_starter_code/a3_starter_code-main/projectfile/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Magic Show</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
  <script src="https://kit.fontawesome.com/5dd3a889b8.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-custom navbar-expand-lg bg-body-tertiary fixed-top bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{url_for('main.index')}}">
                <img src="{{url_for('static', filename='img/logo.png')}}" alt="MagicShow" width="150" height="50">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'event.create' %}active{% endif %}" href="{{ url_for('event.create')}}">Create Event</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'main.history' %}active{% endif %}" href="{{ url_for('main.history')}}">Booking History</a>
                  </li>
                </ul>
              </div>
              <form class="d-flex" role="search" action="{{url_for('main.search')}}">
                <input class="form-control me-2" style="width:50%;" type="search" name="search" id="SearchForm" placeholder="Search Event by Name" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
              </form>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  {% if current_user.is_authenticated %}
                  <li class="nav-item">
                     <a class="nav-link disabled text-muted" href="#">Welcome {{current_user.userName}}</a>
                  </li>
                  <li>
                     <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'auth.login' %}active{% endif %}" href="{{ url_for('auth.login') }}">Sign in</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.endpoint == 'auth.register' %}active{% endif %}" href="{{ url_for('auth.register') }}">Sign up</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>

        <div class="container-fluid">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="container-fluid">
         <div class="row mt-3 mb-3">
            <div class="col-md-12">
            {% for message in messages %}
            <div class="alert alert-info">{{ message }}</div>
            {% endfor %}
         </div>
      </div>
      </div>
      {% endif %}
      {% endwith %}

        {% block header %}
        {% endblock %}
    </header>

    {% block content %}
    {% endblock %}

    <footer class="footer">
        <section class="top">
            <img id="footerimage" src="{{url_for('static', filename='img/logo.png')}}" width="150" height="50" >
            <div class="footer">
              <div class="row footerrow text-left">
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                  <h3>About MagicShow</h3>
                   <ul class="list-unstyled">
                    <li><a>Create event</a></li>
                    <li><a>Explore event</a></li>
                    <li><a>Event marketing platform</a></li>
                    <li><a>E-Ticket available</a></li>
                    <li><a>Create Account</a></li>
                    <li><a>Share experience</a></li>
                  </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                  <h3>Find Events</h3>
                    <ul class="list-unstyled">
                    <li><a>Search by location</a></li>
                    <li><a>In Brisbane</a></li>
                    <li><a>In Sydney</a></li>
                    <li><a>In Melbourne</a></li>
                    <li><a>In Perth</a></li>
                    <li><a>All upcoming events</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                  <h3>Create Events</h3>
                    <ul class="list-unstyled">
                    <li><a>Register</a></li>
                    <li><a>Event details</a></li>
                    <li><a>Magician details</a></li>
                    <li><a>Ticket details</a></li>
                    <li><a>Upload event image</a></li>
                    <li><a>Post comment</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                  <h3>Book Tickets</h3>
                    <ul class="list-unstyled">
                      <li><a>Register</a></li>
                      <li><a>Number of tickets</a></li>
                      <li><a>Type of ticket</a></li>
                      <li><a>Order ticket</a></li>
                      <li><a>Order confirmation id</a></li>
                    </ul>
                </div>
              </div>
            </div>
          </section>
          <section class="bottom">© 2024 MagicShow</section>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

a3_starter_code/a3_starter_code-main/projectfile/website/templates/bhistory.html
{% extends 'base.html' %}
 {% block content %}
  <main>
    <div id="history1" class="container d-flex justify-content-center align-items-center">
      
      <div class="row">
        <h1 id="book1">Booking History</h1>

        {% if bookings %}

        {% for booking in bookings %}
        <div id="first" class="d-flex col-md-11">
          <div class="col-lg-4 col-md-6 col-sm-6">
            <img class="rounded-5" src="{{ url_for('static', filename=booking.event.eventImage) }}" class="rounded-5" width="250px" height="200px">
          </div>
          <div class="col-lg-5 col-md-2">
            <h6 id="write4">{{booking.event.eventName}}</h6>
            
            <h6 id="write3">Location - {{booking.event.eventLocation}}</h6>
            <h6 id="write3">Time & date of booking - {{booking.booked_at.strftime("%d/%m/%Y, %H:%M %p")}}<br>
            </h6>
            <h6 id="write3">Order confirmation id - #{{booking.id}}</h6>
          </div>
          <div id="price" class="col-lg-2 col-md-4">
            <h7 id="write3">Number Of Tickets- {{booking.numTickets}}</h7>
            <h6 id="write3">AUD ${{booking.totalPrice}}</h6>
            <a href="{{url_for('event.show', id=booking.event.id)}}"><button class="btnb">View Details</button></a>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <p>It's time for you to disappear and make some bookings!</p>
        {% endif %}
      </div>
    </div>
    <div class="col-md-10">
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link">Previous</a>
        </li>
        <li class="page-item"><a class="page-link active" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">Next</a>
        </li>
      </ul>
    </div>
  </main>
{% endblock %}

a3_starter_code/a3_starter_code-main/projectfile/website/templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/form.html" as wtf %}
{% block header %}




 
  <main><!--creating the basic image and text formation for the home page-->
      <!--something different that is jombotron-->
      <div class="jumbotron">
<div id="background-image" class="p-5 mb-4 bg-body-tertiary rounded-5" style="background-image: url('{{ url_for('static', filename='img/ph2.png') }}'); color: white;">
          <div class="container-fluid py-5">
            <h1 class="display-2 fw-bold text-white">Welcome to <b>MAGIC SHOW!</b></h1>
            <p class="col-md-8 fs-4 text-white">We hope you enjoy browsing some of the finest events in town on our majestic web app.</p>
            <a href="{{ url_for('event.create') }}">
              <button class="btn btn-outline-light" type="button">Create an event now!</button>
            </a>
          </div>
        </div>
      </div>

     



      <!-- creating cards for showing events-->
    
      {% endblock %}

{% block content %}
<section>
  <div class="container text-center">
    <div class="options">
      <ul id="ul">
        <li id="le"><strong>Categories for Magic shows:</strong></li>
        <li id="li"><a href="{{ url_for('event.filter_by_category', category='Illusion') }}"><button id="opt">Illusion</button></a></li>
        <li id="li"><a href="{{ url_for('event.filter_by_category', category='Comedy') }}"><button id="opt">Comedy</button></a></li>
        <li id="li"><a href="{{ url_for('event.filter_by_category', category='Levitation') }}"><button id="opt">Levitation</button></a></li>
        <li id="li"><a href="{{ url_for('event.filter_by_category', category='Transformation') }}"><button id="opt">Transformation</button></a></li>
        <li id="li"><a href="{{ url_for('event.filter_by_category', category='Mentalism') }}"><button id="opt">Mentalism</button></a></li>
        <li id="li"><a href="{{ url_for('event.filter_by_category', category='Penetration') }}"><button id="opt">Penetration</button></a></li>
      </ul>
    </div>
    <h1 id="headfor1" class="text-white">{{ selected_category if selected_category else 'All' }} Events</h1>
    <div id="rowcard" class="row g-3">
      {% if events %}
        {% for event in events %}
        <div class="col-md-6 col-lg-4 col-xl-3 mb-4">
          <div class="card bg-black rounded-5">
            <div class="image-container">
              <img id="imgcard" src="{{ url_for('static', filename=event.eventImage) }}" alt="{{ event.eventName }}" class="rounded-5" height="200" />
              <div class="overlay-text" id="{{ event.eventStatus.lower() }}"><b>{{ event.eventStatus }}</b></div>
            </div>
            <div class="text text-light p-3">
              <h2>{{ event.eventName }}</h2>
              <h6>({{ event.eventLocation }})</h6>
              <p>On {{ event.eventstartDateTime }}</p>
              <a href="{{ url_for('event.show', id=event.id) }}">
                <button class="btn btn-outline-light">Show Details</button>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <h2>No matching events found.</h2>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}
{% block additional_content %}  

    <section class="gradient-custom">
      <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8 text-center">
          <h2 class="mb-4">Comments on recent events in Brisbane</h2>
        </div>
      </div>
      
    
      <div class="row text-center">
        <div class="col-md-4 mb-5 mb-md-0">
          <div class="d-flex justify-content-center mb-4">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp"
              class="rounded-circle shadow-1-strong" width="150" height="150" />
          </div>
          <h5 class="mb-3">Maria Smantha</h5>
          <p class="px-xl-3">
            <i class="fas fa-quote-left pe-2"></i>Feel the Magic was unique, showcasing the magician's skills, creativity, and ability to entertain. It's was to see the reactions of visitors as they witness seemingly impossible feats, adding to the magic and mystery of the performance.
          </p>
          <ul class="list-unstyled d-flex justify-content-center mb-0">
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star-half-alt fa-sm text-warning"></i>
            </li>
          </ul>
        </div>
        <div class="col-md-4 mb-5 mb-md-0">
          <div class="d-flex justify-content-center mb-4">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp"
              class="rounded-circle shadow-1-strong" width="150" height="150" />
          </div>
          <h5 class="mb-3">Lisa Cudrow</h5>
          <p class="px-xl-3">
            <i class="fas fa-quote-left pe-2"></i>The Blackmantie in QLD was not only entertaining but also inspirational, highlighting the potential and talent of young individuals in the field of magic. It was a delightful experience that left a lasting impression on all who attended.
          </p>
          <ul class="list-unstyled d-flex justify-content-center mb-0">
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
          </ul>
        </div>
        <div class="col-md-4 mb-0">
          <div class="d-flex justify-content-center mb-4">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp"
              class="rounded-circle shadow-1-strong" width="150" height="150" />
          </div>
          <h5 class="mb-3">John Smith</h5>
          <p class="px-xl-3">
            <i class="fas fa-quote-left pe-2"></i>Look Into Eyes magic show offered a form of escapism and entertainment that was both enjoyable and mesmerizing.As watching a grand stage performance ,there was something magical about the experience that kept me as a audience waiting for more.
          </p>
          <ul class="list-unstyled d-flex justify-content-center mb-0">
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="fas fa-star fa-sm text-warning"></i>
            </li>
            <li>
              <i class="far fa-star fa-sm text-warning"></i>
            </li>
          </ul>
        </div>
      </div>
    </section>
  

    
  </main>


  
 


  {% endblock %}

a3_starter_code/a3_starter_code-main/projectfile/website/templates/user.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh; padding-top: 100px;" id="login1">
    <div class="col-md-6">
        <div class="card shadow p-4" id="userform-card">
            <h4 class="text-center mb-4">{{ heading }}</h4>
            {{ render_form(form,extra_classes="in-form")  }}
            {% if heading|lower == 'login' %}
            <p class="text-center mt-3">New user? <a id="loginlink" href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
